
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';

// Load env from backend directory
dotenv.config({ path: path.resolve(__dirname, '../backend/.env') });

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_KEY');
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function setupDatabase() {
    console.log('Setting up database tables...');

    const createNotificationsTable = `
        CREATE TABLE IF NOT EXISTS notifications (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            recipient_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
            recipient_role VARCHAR(50),
            type VARCHAR(50) NOT NULL,
            title VARCHAR(255) NOT NULL,
            message TEXT NOT NULL,
            is_read BOOLEAN DEFAULT FALSE,
            reference_id INTEGER,
            created_at TIMESTAMPTZ DEFAULT NOW()
        );
    `;

    const { error } = await supabase.rpc('exec_sql', { sql: createNotificationsTable });

    // If rpc exec_sql is not available (common in some setups), we might fail here.
    // Alternative: Use a standard query if permissions allow, or just log.
    // Since we are using supabase-js, we usually can't run raw SQL unless there's a helper function in Postgres.

    // fallback: check if we can select from it
    const { error: checkError } = await supabase.from('notifications').select('count', { count: 'exact', head: true });

    if (checkError) {
        console.error('Table "notifications" might be missing or inaccessible:', checkError.message);
        console.log('\nPlease run the following SQL in your Supabase SQL Editor:\n');
        console.log(createNotificationsTable);
    } else {
        console.log('Table "notifications" exists and is accessible.');
    }
}

setupDatabase();
